# http://travis-ci.org/#!/jupyter/kernel_gateway
sudo: false
language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    - pip install --upgrade pip
    - pip install -f travis-wheels/wheelhouse -r dev-requirements.txt .

script:
    - jupyter kernelgateway --help
    - py.test --cov kernel_gateway kernel_gateway/tests -v

after_success:
    - codecov